// src/app/item-details/comment/comment.component.ts
import { Component, Input } from '@angular/core';

import { Comment } from '../../shared/models/comment';

@Component({
  selector: 'app-comment',
  templateUrl: './comment.component.html',
  styleUrls: ['./comment.component.scss']
})
export class CommentComponent {
  @Input() comment: Comment;
  collapse = false;
}

@if (!comment.deleted) {
  <div>
    <div class="meta" [class.meta-collapse]="collapse">
      <span class="collapse" role="button" tabindex="0" (click)="collapse = !collapse"
        (keyup.enter)="collapse = !collapse">[{{collapse ? '+' : '-'}}]</span>
      <a [routerLink]="['/user', comment.user]" routerLinkActive="active">{{comment.user}}</a>
      <span class="time">{{comment.time_ago}}</span>
    </div>
    <div class="comment-tree">
      <div [hidden]="collapse">
        <p class="comment-text" [innerHTML]="comment.content"></p>
        <ul class="subtree">
          @for (subComment of comment.comments; track subComment.id) {
            <li>
              <app-comment [comment]="subComment"></app-comment>
            </li>
          }
        </ul>
      </div>
    </div>
  </div>
}
@if (comment.deleted) {
  <div>
    <div class="deleted-meta">
      <span class="collapse">[deleted]</span> | Comment Deleted
    </div>
  </div>
}

// src/item-details/comment/Comment.tsx
import { useState, type KeyboardEvent } from 'react';
import { NavLink } from 'react-router-dom';

import { Comment } from '../../shared/models';

import './Comment.scss';

interface CommentProps {
    comment: Comment;
}

export default function CommentItem({ comment }: CommentProps) {
    const [collapse, setCollapse] = useState(false);

    const toggleCollapse = () => setCollapse((collapsed) => !collapsed);

    const handleCollapseKeyDown = (event: KeyboardEvent<HTMLSpanElement>) => {
        if (event.key === 'Enter' || event.key === ' ') {
            event.preventDefault();
            toggleCollapse();
        }
    };

    if (comment.deleted) {
        return (
            <div className="comment">
                <div className="deleted-meta">
                    <span className="collapse">[deleted]</span> | Comment Deleted
                </div>
            </div>
        );
    }

    return (
        <div className="comment">
            <div className={collapse ? 'meta meta-collapse' : 'meta'}>
                <span
                    className="collapse"
                    role="button"
                    tabIndex={0}
                    onClick={toggleCollapse}
                    onKeyDown={handleCollapseKeyDown}
                >
                    [{collapse ? '+' : '-'}]
                </span>{' '}
                <NavLink className={({ isActive }) => (isActive ? 'active' : undefined)} to={`/user/${comment.user}`}>
                    {comment.user}
                </NavLink>
                <span className="time">{comment.time_ago}</span>
            </div>
            <div className="comment-tree">
                <div hidden={collapse}>
                    <p className="comment-text" dangerouslySetInnerHTML={{ __html: comment.content ?? '' }}></p>
                    <ul className="subtree">
                        {comment.comments?.map((subComment) => (
                            <li key={subComment.id}>
                                <CommentItem comment={subComment} />
                            </li>
                        ))}
                    </ul>
                </div>
            </div>
        </div>
    );
}
