// src/app/shared/components/error-message/error-message.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-error-message',
  templateUrl: './error-message.component.html',
  styleUrls: ['./error-message.component.scss']
})
export class ErrorMessageComponent {
  @Input() message: string;
}

<div class="error-section" role="alert">
    <div class="error-badge">!</div>
    <p class="strong">{{ message() }}</p>
    <p>
        Your cashback data could not be loaded. If you are offline, visit this page once with a network connection so it
        can be cached for offline use.
    </p>
</div>

// src/shared/components/ErrorMessage.tsx
import './ErrorMessage.scss';

export function ErrorMessage({ message }: { message: string }) {
    return (
        <div className="error-section">
            <div className="skull">
                <div className="head">
                    <div className="crack"></div>
                </div>
                <div className="mouth">
                    <div className="teeth"></div>
                </div>
            </div>
            <p className="strong">{message}</p>
            <p>
                If you are offline viewing, you'll need to visit this page with a network connection first before it can
                work offline.
            </p>
        </div>
    );
}
