// src/app/item-details/comment/comment.component.ts
import { Component, Input } from '@angular/core';

import { Comment } from '../../shared/models/comment';

@Component({
  selector: 'app-comment',
  templateUrl: './comment.component.html',
  styleUrls: ['./comment.component.scss']
})
export class CommentComponent {
  @Input() comment: Comment;
  collapse = false;
}

@if (!comment.deleted) {
  <div>
    <div class="meta" [class.meta-collapse]="collapse">
      <span class="collapse" role="button" tabindex="0" (click)="collapse = !collapse"
        (keyup.enter)="collapse = !collapse">[{{collapse ? '+' : '-'}}]</span>
      <a [routerLink]="['/user', comment.user]" routerLinkActive="active">{{comment.user}}</a>
      <span class="time">{{comment.time_ago}}</span>
    </div>
    <div class="comment-tree">
      <div [hidden]="collapse">
        <p class="comment-text" [innerHTML]="comment.content"></p>
        <ul class="subtree">
          @for (subComment of comment.comments; track subComment.id) {
            <li>
              <app-comment [comment]="subComment"></app-comment>
            </li>
          }
        </ul>
      </div>
    </div>
  </div>
}
@if (comment.deleted) {
  <div>
    <div class="deleted-meta">
      <span class="collapse">[deleted]</span> | Comment Deleted
    </div>
  </div>
}

// react/src/features/item/Comment.tsx
import { useState } from 'react';
import { Link } from 'react-router-dom';

import type { Comment as CommentModel } from '../../shared/models';

import './Comment.scss';

export function Comment({ comment }: { comment: CommentModel }) {
    const [collapse, setCollapse] = useState(false);

    if (comment.deleted) {
        return (
            <div className="comment">
                <div className="deleted-meta">
                    <span className="collapse">[deleted]</span> | Comment Deleted
                </div>
            </div>
        );
    }

    return (
        <div className="comment">
            <div className={collapse ? 'meta meta-collapse' : 'meta'}>
                <span className="collapse" onClick={() => setCollapse(!collapse)}>
                    [{collapse ? '+' : '-'}]
                </span>{' '}
                <Link to={`/user/${comment.user}`}>{comment.user}</Link>{' '}
                <span className="time">{comment.time_ago}</span>
            </div>
            <div className="comment-tree">
                <div hidden={collapse}>
                    <p className="comment-text" dangerouslySetInnerHTML={{ __html: comment.content }} />
                    <ul className="subtree">
                        {comment.comments.map((subComment) => (
                            <li key={subComment.id}>
                                <Comment comment={subComment} />
                            </li>
                        ))}
                    </ul>
                </div>
            </div>
        </div>
    );
}
