// react/src/core/Header/Header.tsx
import { NavLink } from 'react-router-dom';

import { useSettings } from '../../shared/settings/useSettings';
import { Settings } from '../Settings/Settings';
import './Header.scss';

function scrollTop(): void {
    window.scrollTo(0, 0);
}

function activeClassName({ isActive }: { isActive: boolean }): string | undefined {
    return isActive ? 'active' : undefined;
}

export function Header() {
    const { settings, toggleSettings } = useSettings();

    return (
        <header>
            <div id="header">
                <NavLink
                    to="/news/1"
                    className={({ isActive }) => (isActive ? 'home-link active' : 'home-link')}
                    onClick={scrollTop}
                >
                    <div className="logo-inner"></div>
                    <img className="logo" src="/assets/images/logo.svg" alt="Logo" />
                </NavLink>
                <div className="header-text">
                    <div className="left">
                        <span className="header-nav">
                            <NavLink to="/newest/1" className={activeClassName} onClick={scrollTop}>
                                new
                            </NavLink>
                            {' | '}
                            <NavLink to="/show/1" className={activeClassName} onClick={scrollTop}>
                                show
                            </NavLink>
                            {' | '}
                            <NavLink to="/ask/1" className={activeClassName} onClick={scrollTop}>
                                ask
                            </NavLink>
                            {' | '}
                            <NavLink to="/jobs/1" className={activeClassName} onClick={scrollTop}>
                                jobs
                            </NavLink>
                        </span>
                    </div>
                </div>
                <div className="info">
                    <img className="settings" src="/assets/images/cog.svg" alt="Settings" onClick={toggleSettings} />
                </div>
            </div>
            {settings.showSettings && <Settings />}
        </header>
    );
}

// src/app/core/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

import { SettingsComponent } from '../settings/settings.component';
import { SettingsService } from '../../shared/services/settings.service';
import { Settings } from '../../shared/models/settings';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, SettingsComponent],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent {
  settings: Settings;

  constructor(private _settingsService: SettingsService) {
    this.settings = this._settingsService.settings;
  }

  toggleSettings(): void {
    this._settingsService.toggleSettings();
  }

  scrollTop(): void {
    window.scrollTo(0, 0);
  }
}

<header>
    <div id="header">
      <a class="home-link" routerLink="/news/1" routerLinkActive="active" (click)="scrollTop()">
        <div class="logo-inner"></div>
        <img class="logo" src="assets/images/logo.svg" alt="Logo">
      </a>
      <div class="header-text">
        <div class="left">
          <span class="header-nav">
            <a routerLink="/newest/1" routerLinkActive="active" (click)="scrollTop()">new</a>
              |
            <a routerLink="/show/1" routerLinkActive="active" (click)="scrollTop()">show</a>
              |
            <a routerLink="/ask/1" routerLinkActive="active" (click)="scrollTop()">ask</a>
              |
            <a routerLink="/jobs/1" routerLinkActive="active" (click)="scrollTop()">jobs</a>
          </span>
        </div>
      </div>
      <div class="info">
        <img class="settings" src="assets/images/cog.svg" alt="Settings" role="button" tabindex="0" (click)="toggleSettings()" (keydown.enter)="toggleSettings()">
      </div>
    </div>
    @if (settings.showSettings) {
      <app-settings></app-settings>
    }
  </header>
