// react-app/src/components/core/Header.tsx
import { Link } from 'react-router-dom';
import { useSettings } from '../../context/SettingsContext';
import Settings from './Settings';
import './Header.scss';

function Header() {
  const { settings, toggleSettings } = useSettings();

  const scrollTop = () => {
    window.scrollTo(0, 0);
  };

  return (
    <header>
      <div id="header">
        <Link className="home-link" to="/news/1" onClick={scrollTop}>
          <div className="logo-inner"></div>
          <img className="logo" src="/assets/images/logo.svg" alt="Logo" />
        </Link>
        <div className="header-text">
          <div className="left">
            <span className="header-nav">
              <Link to="/newest/1" onClick={scrollTop}>new</Link>
              {' | '}
              <Link to="/show/1" onClick={scrollTop}>show</Link>
              {' | '}
              <Link to="/ask/1" onClick={scrollTop}>ask</Link>
              {' | '}
              <Link to="/jobs/1" onClick={scrollTop}>jobs</Link>
            </span>
          </div>
        </div>
        <div className="info">
          <img 
            className="settings" 
            src="/assets/images/cog.svg" 
            alt="Settings" 
            onClick={toggleSettings}
          />
        </div>
      </div>
      {settings.showSettings && <Settings />}
    </header>
  );
}

export default Header;

// src/app/core/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

import { SettingsComponent } from '../settings/settings.component';
import { SettingsService } from '../../shared/services/settings.service';
import { Settings } from '../../shared/models/settings';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, SettingsComponent],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent {
  settings: Settings;

  constructor(private _settingsService: SettingsService) {
    this.settings = this._settingsService.settings;
  }

  toggleSettings(): void {
    this._settingsService.toggleSettings();
  }

  scrollTop(): void {
    window.scrollTo(0, 0);
  }
}

<header>
    <div id="header">
      <a class="home-link" routerLink="/news/1" routerLinkActive="active" (click)="scrollTop()">
        <div class="logo-inner"></div>
        <img class="logo" src="assets/images/logo.svg" alt="Logo">
      </a>
      <div class="header-text">
        <div class="left">
          <span class="header-nav">
            <a routerLink="/newest/1" routerLinkActive="active" (click)="scrollTop()">new</a>
              |
            <a routerLink="/show/1" routerLinkActive="active" (click)="scrollTop()">show</a>
              |
            <a routerLink="/ask/1" routerLinkActive="active" (click)="scrollTop()">ask</a>
              |
            <a routerLink="/jobs/1" routerLinkActive="active" (click)="scrollTop()">jobs</a>
          </span>
        </div>
      </div>
      <div class="info">
        <img class="settings" src="assets/images/cog.svg" alt="Settings" role="button" tabindex="0" (click)="toggleSettings()" (keydown.enter)="toggleSettings()">
      </div>
    </div>
    @if (settings.showSettings) {
      <app-settings></app-settings>
    }
  </header>
