// src/app/user/user.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs/Subscription';

import { HackerNewsAPIService } from '../shared/services/hackernews-api.service';
import { User } from '../shared/models/user';

@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.scss']
})
export class UserComponent implements OnInit {
  sub: Subscription;
  user: User;
  errorMessage = '';

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private route: ActivatedRoute,
    private _location: Location
  ) {}

  ngOnInit() {
    this.sub = this.route.params.subscribe(params => {
      const userID = params['id'];
      this._hackerNewsAPIService.fetchUser(userID).subscribe(data => {
        this.user = data;
      }, error => this.errorMessage = 'Could not load user ' + userID + '.');
    });
  }

  goBack() {
    this._location.back();
  }
}

<app-loader *ngIf="!user && !errorMessage"></app-loader>
<app-error-message [message]="errorMessage" *ngIf="!user && errorMessage !== ''"></app-error-message>

<div *ngIf="user" class="profile">
  <div class="mobile item-header">
    <p class="title-block">
      <span class="back-button" (click)="goBack()"></span>
      Profile: {{ user.id }}
    </p>
  </div>
  <div class="main-details">
    <span class="name">{{ user.id }}</span>
    <span class="right">{{ user.karma }} ★</span>
    <p class="age">Created {{ user.created }}</p>
  </div>
  <div class="other-details" *ngIf="user.about">
    <p [innerHTML]="user.about"></p>
  </div>
  <div class="external-links">
    <a href="https://news.ycombinator.com/submitted?id={{user.id}}" target="_blank" rel="noopener">View submissions on HN</a>
    <a href="https://news.ycombinator.com/favorites?id={{user.id}}" target="_blank" rel="noopener">View favorites on HN</a>
  </div>
</div>

// react-app/src/components/User/User.tsx
import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { fetchUser } from '../../services/hackernews-api';
import type { User as UserType } from '../../models/types';
import Loader from '../Loader/Loader';
import ErrorMessage from '../ErrorMessage/ErrorMessage';
import './User.scss';

export default function User() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [user, setUser] = useState<UserType | null>(null);
  const [errorMessage, setErrorMessage] = useState('');

  useEffect(() => {
    setUser(null);
    setErrorMessage('');
    if (id) {
      fetchUser(id)
        .then((data) => {
          setUser(data);
        })
        .catch(() => {
          setErrorMessage(`Could not load user ${id}.`);
        });
    }
  }, [id]);

  const goBack = () => {
    navigate(-1);
  };

  return (
    <>
      {!user && !errorMessage && <Loader />}
      {!user && errorMessage !== '' && <ErrorMessage message={errorMessage} />}

      {user && (
        <div className="profile">
          <div className="mobile item-header">
            <p className="title-block">
              <span className="back-button" onClick={goBack}></span>
              Profile: {user.id}
            </p>
          </div>
          <div className="main-details">
            <span className="name">{user.id}</span>
            <span className="right">{user.karma} ★</span>
            <p className="age">Created {user.created}</p>
          </div>
          {user.about && (
            <div className="other-details">
              <p dangerouslySetInnerHTML={{ __html: user.about }} />
            </div>
          )}
        </div>
      )}
    </>
  );
}
