// src/react/item-details/ItemDetails.tsx
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';

import { fetchItemContent } from '../../api/hackernews';
import '../../app/item-details/item-details.component.scss';
import { Story } from '../models/story';
import { content, host } from '../scope';
import { ErrorMessage } from '../shared/ErrorMessage';
import { Loader } from '../shared/Loader';
import { comment as commentCount } from '../shared/comment';
import { useSettings } from '../settings/SettingsContext';
import { Comment } from './Comment';

const c = content('item-details');

type ItemContent = Story & { text?: string; content?: string };

export function ItemDetails() {
    const { id } = useParams();
    const navigate = useNavigate();
    const { settings } = useSettings();

    const [item, setItem] = useState<ItemContent | undefined>(undefined);
    const [errorMessage, setErrorMessage] = useState('');

    useEffect(() => {
        let cancelled = false;

        fetchItemContent(Number(id)).then(
            loaded => {
                if (!cancelled) {
                    setItem(loaded);
                }
            },
            () => {
                if (!cancelled) {
                    setErrorMessage('Could not load item comments.');
                }
            }
        );

        return () => {
            cancelled = true;
        };
    }, [id]);

    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    const hasUrl = item ? item.url.indexOf('http') === 0 : false;
    const target = settings.openLinkInNewTab ? '_blank' : undefined;
    const rel = settings.openLinkInNewTab ? 'noopener' : undefined;

    return (
        <div className="main-content" {...c}>
            {!item && errorMessage === '' && (
                <app-loader {...c} {...host('loader')}>
                    <Loader />
                </app-loader>
            )}
            {!item && errorMessage !== '' && (
                <app-error-message {...c} {...host('error-message')}>
                    <ErrorMessage message={errorMessage} />
                </app-error-message>
            )}

            {item && (
                <div className="item" {...c}>
                    <div className="mobile item-header" {...c}>
                        <p className="title-block" {...c}>
                            <span className="back-button" onClick={() => navigate(-1)} {...c}></span>
                            {hasUrl ? (
                                <a className="title" href={item.url} target={target} rel={rel} {...c}>
                                    {item.title}
                                </a>
                            ) : (
                                <Link className="title" to={`/item/${item.id}`} {...c}>
                                    {item.title}
                                </Link>
                            )}
                        </p>
                    </div>
                    <div
                        className={[
                            'laptop',
                            item.comments_count > 0 || item.type === 'job' ? 'item-header' : null,
                            item.text ? 'head-margin' : null,
                        ]
                            .filter(Boolean)
                            .join(' ')}
                        {...c}
                    >
                        {hasUrl ? (
                            <p {...c}>
                                <a className="title" href={item.url} target={target} rel={rel} {...c}>
                                    {item.title}
                                </a>{' '}
                                {item.domain && (
                                    <span className="domain" {...c}>
                                        ({item.domain})
                                    </span>
                                )}
                            </p>
                        ) : (
                            <p {...c}>
                                <Link className="title" to={`/item/${item.id}`} {...c}>
                                    {item.title}
                                </Link>
                            </p>
                        )}
                        <div className="subtext" {...c}>
                            {item.type !== 'job' && (
                                <span {...c}>
                                    {item.points} points by{' '}
                                    <Link to={`/user/${item.user}`} {...c}>
                                        {item.user}
                                    </Link>
                                </span>
                            )}
                            <span className={item.type !== 'job' ? 'item-details' : undefined} {...c}>
                                {item.time_ago}
                                {item.type !== 'job' && (
                                    <span {...c}>
                                        {' '}
                                        |{' '}
                                        <Link to={`/item/${item.id}`} {...c}>
                                            {commentCount(item.comments_count)}
                                        </Link>
                                    </span>
                                )}
                            </span>
                        </div>
                    </div>
                    {item.type === 'poll' && (
                        <div className="pollResults" {...c}>
                            {item.poll.map((pollResult, index) => (
                                <div key={index} className="pollContent" {...c}>
                                    <div dangerouslySetInnerHTML={{ __html: pollResult.content }} {...c}></div>
                                    <div className="subtext" {...c}>
                                        {pollResult.points} points
                                    </div>
                                    <div
                                        className="pollBar"
                                        style={{ width: `${(pollResult.points / item.poll_votes_count) * 100}%` }}
                                        {...c}
                                    ></div>
                                </div>
                            ))}
                        </div>
                    )}
                    <p className="subject" dangerouslySetInnerHTML={{ __html: item.content ?? '' }} {...c}></p>
                    <ul className="comment-list" {...c}>
                        {(item.comments ?? []).map(itemComment => (
                            <li key={itemComment.id} {...c}>
                                <app-comment {...c} {...host('comment')}>
                                    <Comment comment={itemComment} />
                                </app-comment>
                            </li>
                        ))}
                    </ul>
                </div>
            )}
        </div>
    );
}

// src/app/item-details/item-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs/Subscription';

import { HackerNewsAPIService } from '../shared/services/hackernews-api.service';
import { SettingsService } from '../shared/services/settings.service';

import { Story } from '../../models/story';
import { Settings } from '../../models/settings';

@Component({
  selector: 'app-item-details',
  templateUrl: './item-details.component.html',
  styleUrls: ['./item-details.component.scss']
})
export class ItemDetailsComponent implements OnInit {
  sub: Subscription;
  item: Story;
  errorMessage = '';
  settings: Settings;

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private _settingsService: SettingsService,
    private route: ActivatedRoute,
    private _location: Location
  ) {
    this.settings = this._settingsService.settings;
  }

  ngOnInit() {
    this.sub = this.route.params.subscribe(params => {
      let itemID = +params['id'];
      this._hackerNewsAPIService.fetchItemContent(itemID).subscribe(item => {
        this.item = item;
      }, error => this.errorMessage = 'Could not load item comments.');
    });
    window.scrollTo(0, 0);
  }

  goBack() {
    this._location.back();
  }

  get hasUrl(): boolean {
    return this.item.url.indexOf('http') === 0;
  }

}

<div class="main-content">
  @if (!item && !errorMessage) {
    <app-loader></app-loader>
  }
  @if (!item && errorMessage !== '') {
    <app-error-message [message]="errorMessage"></app-error-message>
  }

  @if (item) {
    <div class="item">
      <div class="mobile item-header">
        <p class="title-block">
          <span class="back-button" role="button" tabindex="0" aria-label="Go back" (click)="goBack()"
            (keyup.enter)="goBack()"></span>
          @if (hasUrl) {
            <a class="title" href="{{item.url}}" [attr.target]="settings.openLinkInNewTab ? '_blank' : null" [attr.rel]="settings.openLinkInNewTab ? 'noopener' : null">
              {{item.title}}
            </a>
          }
          @if (!hasUrl) {
            <a class="title" [routerLink]="['/item', item.id]"
              routerLinkActive="active">
              {{item.title}}
            </a>
          }
        </p>
      </div>
      <div class="laptop" [class.item-header]="item.comments_count > 0 || item.type === 'job'" [class.head-margin]="item.text">
        @if (hasUrl) {
          <p>
            <a class="title" href="{{item.url}}" [attr.target]="settings.openLinkInNewTab ? '_blank' : null" [attr.rel]="settings.openLinkInNewTab ? 'noopener' : null">
              {{item.title}}
            </a>
            @if (item.domain) {
              <span class="domain">({{item.domain}})</span>
            }
          </p>
        }
        @if (!hasUrl) {
          <p>
            <a class="title" [routerLink]="['/item', item.id]" routerLinkActive="active">
              {{item.title}}
            </a>
          </p>
        }
        <div class="subtext">
          @if (item.type !== 'job') {
            <span>
              {{item.points}} points by
              <a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a>
            </span>
          }
          <span [class.item-details]="item.type !== 'job'">
            {{item.time_ago}}
            @if (item.type !== 'job') {
              <span> |
                <a [routerLink]="['/item', item.id]" routerLinkActive="active">
                  {{item.comments_count | comment }}
                </a>
              </span>
            }
          </span>
        </div>
      </div>
      @if (item.type === 'poll') {
        <div class="pollResults">
          @for (pollResult of item.poll; track $index) {
            <div class="pollContent">
              <div [innerHTML]="pollResult.content"></div>
              <div class="subtext">{{pollResult.points}} points</div>
              <div class="pollBar" [ngStyle]="{'width': pollResult.points/item.poll_votes_count*100+'%'}"></div>
            </div>
          }
        </div>
      }
      <p class="subject" [innerHTML]="item.content"></p>
      <ul class="comment-list">
        @for (comment of item.comments; track comment.id) {
          <li >
            <app-comment [comment]="comment"></app-comment>
          </li>
        }
      </ul>
    </div>
  }
</div>
