// src/app/core/settings/Settings.tsx
import { useSettings } from '../../shared/services/settings.service';
import './settings.scss';

export function SettingsPanel() {
    const { settings, toggleSettings, toggleOpenLinksInNewTab, setTheme, setFont, setSpacing } = useSettings();

    return (
        <div id="popup1" className="overlay">
            <div className="popup">
                <h1>Settings</h1>
                <hr />
                <span className="close" onClick={toggleSettings}>
                    &times;
                </span>
                <div className="content">
                    <div className="control-section">
                        <h2>Links</h2>
                        <input
                            type="checkbox"
                            checked={settings.openLinkInNewTab}
                            onChange={toggleOpenLinksInNewTab}
                        />{' '}
                        Open links in a new tab
                    </div>
                    <div className="theme-controls">
                        <div className="control-section">
                            <h2>Select a theme</h2>
                            <div>
                                <label>
                                    <input
                                        name="theme"
                                        type="radio"
                                        value="default"
                                        checked={settings.theme === 'default'}
                                        onChange={() => setTheme('default')}
                                    />{' '}
                                    Default
                                </label>
                            </div>
                            <div>
                                <label>
                                    <input
                                        name="theme"
                                        type="radio"
                                        value="night"
                                        checked={settings.theme === 'night'}
                                        onChange={() => setTheme('night')}
                                    />{' '}
                                    Night
                                </label>
                            </div>
                            <div>
                                <label>
                                    <input
                                        name="theme"
                                        type="radio"
                                        value="amoledblack"
                                        checked={settings.theme === 'amoledblack'}
                                        onChange={() => setTheme('amoledblack')}
                                    />{' '}
                                    Black (AMOLED)
                                </label>
                            </div>
                        </div>
                        <div className="control-section">
                            <h2>Change Font</h2>
                            <div>
                                <label>
                                    Font size:
                                    <input
                                        min="1"
                                        value={settings.titleFontSize}
                                        name="titleFont"
                                        type="number"
                                        onChange={(e) => setFont(e.target.value)}
                                    />
                                </label>
                            </div>
                            <div>
                                <label>
                                    List spacing:
                                    <input
                                        min="0"
                                        value={settings.listSpacing}
                                        name="listSpacing"
                                        type="number"
                                        onChange={(e) => setSpacing(e.target.value)}
                                    />
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

// src/app/core/settings/settings.component.ts
import { Component, inject } from '@angular/core';

import { Settings } from '../../shared/models/settings';
import { SettingsService } from '../../shared/services/settings.service';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.scss'],
})
export class SettingsComponent {
  private readonly settingsService = inject(SettingsService);

  settings: Settings = this.settingsService.settings;

  closeSettings() {
    this.settingsService.toggleSettings();
  }

  toggleOpenLinksInNewTab() {
    this.settingsService.toggleOpenLinksInNewTab();
  }

  selectTheme(theme: string) {
    this.settingsService.setTheme(theme);
  }

  changeTitleFont(fontSize: string) {
    this.settingsService.setFont(fontSize);
  }

  changeSpacing(listSpacing: string) {
    this.settingsService.setSpacing(listSpacing);
  }
}

<div id="popup1" class="overlay">
    <div class="popup">
        <h1>Settings</h1>
        <hr>
        <span class="close" (click)="closeSettings()">&times;</span>
        <div class="content">
            <div class="control-section">
                <h2>Links</h2>
                <input 
                    type="checkbox" 
                    [checked]="settings.openLinkInNewTab" 
                    (change)="toggleOpenLinksInNewTab()" />
                    Open links in a new tab
            </div>
            <div class="theme-controls">
                <div class="control-section">
                    <h2>Select a theme</h2>
                    <div>
                        <label>
                        <input #default 
                            name="theme" 
                            type="radio" 
                            value="default" 
                            [checked]="settings.theme === default.value"
                            (click)="selectTheme(default.value)" />
                            Default
                        </label>
                    </div>
                    <div>
                        <label>
                        <input #night 
                            name="theme" 
                            type="radio" 
                            value="night" 
                            [checked]="settings.theme === night.value" 
                            (click)="selectTheme(night.value)" />
                            Night
                        </label>
                    </div>
                    <div>
                        <label>
                        <input 
                            #amoledblack 
                            name="theme" 
                            type="radio" 
                            value="amoledblack" 
                            [checked]="settings.theme === amoledblack.value"
                            (click)="selectTheme(amoledblack.value)" />
                            Black (AMOLED)
                        </label>
                    </div>
                    <div>
                        <label>
                        <input 
                            #blackwhite 
                            name="theme" 
                            type="radio" 
                            value="blackwhite" 
                            [checked]="settings.theme === blackwhite.value"
                            (click)="selectTheme(blackwhite.value)" />
                            Black & White
                        </label>
                    </div>
                </div>
                <div class="control-section">
                    <h2>Change Font</h2>
                    <div>
                        <label>
                        Font size:
                        <input 
                            #titleFont 
                            min="1" 
                            [value]="settings.titleFontSize" 
                            name="theme" 
                            type="number" 
                            (keyup)="changeTitleFont(titleFont.value)" />
                        </label>
                    </div>
                    <div>
                        <label>
                        List spacing:
                        <input 
                            #listSpacing 
                            min="0" 
                            [value]="settings.listSpacing" 
                            name="theme" 
                            type="number" 
                            (keyup)="changeSpacing(listSpacing.value)" />
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
